const groupSettingsForm = [
	{
		asyncValidators: null,
		errorMessages: null,
		hidden: false,
		id: 'group',
		label: null,
		labelTooltip: null,
		controlTooltip: null,
		layout: null,
		name: 'group',
		relations: [],
		updateOn: null,
		validators: null,
		disabled: false,
		group: [
			{
				asyncValidators: null,
				errorMessages: null,
				hidden: false,
				id: 'name',
				label: 'Name',
				labelTooltip: null,
				controlTooltip: null,
				layout: null,
				name: 'name',
				relations: [],
				updateOn: null,
				validators: null,
				disabled: false,
				additional: null,
				hint: null,
				required: true,
				tabIndex: null,
				value: null,
				autoComplete: 'on',
				autoFocus: false,
				maxLength: null,
				minLength: null,
				placeholder: '',
				prefix: null,
				readOnly: false,
				spellCheck: false,
				suffix: null,
				list: null,
				type: 'INPUT',
				accept: null,
				inputType: 'text',
				mask: null,
				max: null,
				min: null,
				multiple: null,
				pattern: null,
				step: null,
			},
			{
				asyncValidators: null,
				errorMessages: null,
				hidden: false,
				id: 'description',
				label: 'Description',
				labelTooltip: null,
				controlTooltip: null,
				layout: null,
				name: 'description',
				relations: [],
				updateOn: null,
				validators: null,
				disabled: false,
				additional: null,
				hint: null,
				required: true,
				tabIndex: null,
				value: null,
				autoComplete: 'on',
				autoFocus: false,
				maxLength: null,
				minLength: null,
				placeholder: '',
				prefix: null,
				readOnly: false,
				spellCheck: false,
				suffix: null,
				type: 'TEXTAREA',
				cols: 20,
				rows: 2,
				wrap: 'soft',
			},
			{
				asyncValidators: null,
				errorMessages: null,
				hidden: false,
				id: 'isVisible',
				label: 'Visible',
				labelTooltip: null,
				controlTooltip: null,
				layout: null,
				name: 'isVisible',
				relations: [],
				updateOn: null,
				validators: null,
				disabled: false,
				additional: null,
				hint: null,
				required: true,
				tabIndex: null,
				value: false,
				labelPosition: null,
				type: 'CHECKBOX',
				indeterminate: false,
			},
			{
				asyncValidators: null,
				errorMessages: null,
				hidden: false,
				id: 'textColor',
				label: 'Text Color',
				labelTooltip: null,
				controlTooltip: null,
				layout: null,
				name: 'textColor',
				relations: [],
				updateOn: null,
				validators: null,
				disabled: false,
				additional: null,
				hint: null,
				required: true,
				tabIndex: null,
				value: null,
				type: 'COLORPICKER',
				format: 'hex',
				inline: false,
			},
			{
				asyncValidators: null,
				errorMessages: null,
				hidden: false,
				id: 'backgroundColor',
				label: 'Background Color',
				labelTooltip: null,
				controlTooltip: null,
				layout: null,
				name: 'backgroundColor',
				relations: [],
				updateOn: null,
				validators: null,
				disabled: false,
				additional: null,
				hint: null,
				required: true,
				tabIndex: null,
				value: null,
				type: 'COLORPICKER',
				format: 'hex',
				inline: false,
			},
		],
		type: 'GROUP',
		legend: null,
	},
];

export default groupSettingsForm;
